#!/bin/bash

DATA=$(cd $(dirname $0); pwd)

cd $DATA || exit -1
blender -b blue.blend -P $DATA/import-actions.py || exit -1
blender -b red.blend -P $DATA/import-actions.py || exit -1
blender -b green.blend -P $DATA/import-flip-actions.py || exit -1
blender -b yellow.blend -P $DATA/import-flip-actions.py || exit -1
cd $DATA/../extra || exit -1
blender -b miku.blend -P $DATA/import-actions.py || exit -1
blender -b rin.blend -P $DATA/import-actions.py || exit -1
blender -b ren.blend -P $DATA/import-flip-actions.py || exit -1
blender -b haku.blend -P $DATA/import-actions.py || exit -1
blender -b naruto.blend -P $DATA/import-actions.py || exit -1
